"""added created at and updated at to project table

Revision ID: 044650040809
Revises: 0dad0f2acbda
Create Date: 2023-06-16 21:22:09.055801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044650040809'
down_revision = '0dad0f2acbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
