"""renamed column

Revision ID: 32dfb447bb1d
Revises: a49f64ff9a31
Create Date: 2023-06-18 15:09:08.601250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32dfb447bb1d'
down_revision = 'a49f64ff9a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('git_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('github_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('git_url')

    # ### end Alembic commands ###
