"""renamed columns

Revision ID: 4e94739210d7
Revises: b1813c08753a
Create Date: 2024-01-08 23:17:00.166900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e94739210d7'
down_revision = 'b1813c08753a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bugs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.drop_column('fixed')

    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.drop_column('done')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('done', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('completed')

    with op.batch_alter_table('bugs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fixed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
