"""created bugs table

Revision ID: 7c794b9478a7
Revises: bcd05c064620
Create Date: 2023-06-19 22:05:20.203375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c794b9478a7'
down_revision = 'bcd05c064620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bug', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bugs')
    # ### end Alembic commands ###
