"""renamed column again

Revision ID: bbeb0a7d17db
Revises: fae733d3a9a8
Create Date: 2023-12-01 23:55:27.335164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbeb0a7d17db'
down_revision = 'fae733d3a9a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.String(length=255), nullable=False))
        batch_op.drop_column('events')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('events', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('event')

    # ### end Alembic commands ###
