"""modifed todo-bugs

Revision ID: d1220a65cd68
Revises: f6bed2a5a95d
Create Date: 2023-10-24 23:21:08.275102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1220a65cd68'
down_revision = 'f6bed2a5a95d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bugs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bug_info', sa.String(length=255), nullable=True))
        batch_op.alter_column('bug',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('todo',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('todo',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('bugs', schema=None) as batch_op:
        batch_op.alter_column('bug',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('bug_info')

    # ### end Alembic commands ###
