"""renamed column

Revision ID: fae733d3a9a8
Revises: 9d7042592b95
Create Date: 2023-12-01 23:54:16.040481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae733d3a9a8'
down_revision = '9d7042592b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('events', sa.String(length=255), nullable=False))
        batch_op.drop_column('event')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('events')

    # ### end Alembic commands ###
